Repository SprintPart2Team10/openmind, pull requests merged in 2023-12, with the labels that each got.

#1 Feat: button/box 구현
  src/components/common/ButtonBox/ButtonBox.jsx
  src/components/common/ButtonBox/ButtonBox.module.css
Labels: 리뷰 완료

#7 Feat: badge 구현
  src/components/common/Badge/Badge.jsx
  src/components/common/Badge/Badge.module.css
Labels: 리뷰 완료

#6 Feat: 입력 필드 구현
  src/components/common/InputField/InputField.jsx
  src/components/common/InputField/InputField.module.css
  src/images/icons/person.svg
Labels: 리뷰 완료

#2 Feat: button/floating 구현
  src/components/common/ButtonFloating/ButtonFloating.jsx
  src/components/common/ButtonFloating/ButtonFloating.module.css
Labels: 리뷰 완료

#3 Feat: InputTextarea 구현
  src/components/common/InputTextarea/InputTextarea.jsx
  src/components/common/InputTextarea/InputTextarea.module.css
Labels: 리뷰 완료

#4 Feat: Reaction 구현
  src/components/Reaction/Reaction.jsx
  src/components/Reaction/Reaction.module.css
Labels: 리뷰 완료

#8 Feat: sharebox 및 toast 구현
  src/components/common/Button/LinkBox.jsx
  src/components/common/Button/ShareBox.jsx
  src/components/common/Button/ShareBox.module.css
  src/components/common/Button/SnsBox.jsx
  src/components/common/Button/SnsBox.module.css
  src/components/common/Button/Toast.jsx
  src/components/common/Button/Toast.module.css
  src/images/linkBrown.svg
Labels: DONE

#9 Feat : 사용자 카드 컴포넌트 구현
  src/components/common/UserCard/data-access-card/test.js
  src/components/common/UserCard/ui-card/UserCard.jsx
  src/components/common/UserCard/ui-card/UserCard.module.css
  src/pages/list/ListPage.jsx
  src/pages/list/ListPage.module.css
Labels: 리뷰 요청, 수정 완료

#11 Feat: Dropdown 정렬 컴포넌트 구현
  src/components/common/DropdownOrder/DropdownOrder.jsx
  src/components/common/DropdownOrder/DropdownOrder.module.css
Labels: 리뷰 요청, 수정 완료

#12 Feat: Dropdown 케밥 컴포넌트 구현
  src/components/common/DropdownKebab/DropdownKebab.jsx
  src/components/common/DropdownKebab/DropdownKebab.module.css
Labels: 리뷰 요청, 수정 완료

#13 Feat : 답변 컴포넌트 구현
  src/components/common/FeedCardAnswer/Answer/Answer.jsx
  src/components/common/FeedCardAnswer/Answer/Answer.module.css
  src/components/common/FeedCardAnswer/AnswerLayout/AnswerLayout.jsx
  src/components/common/FeedCardAnswer/AnswerLayout/AnswerLayout.module.css
  src/components/common/FeedCardAnswer/AnswerTextArea/AnswerTextArea.jsx
  src/components/common/FeedCardAnswer/AnswerTextArea/AnswerTextArea.module.css
  src/pages/answer/AnswerPage.jsx
Labels: 리뷰 요청

#24 Feat: post/{id} 페이지 구현
  src/components/common/Reaction/Reaction.jsx
  src/components/common/Reaction/Reaction.module.css
  src/components/postpage/FeedCard/FeedCard.jsx
  src/components/postpage/FeedCard/FeedCard.module.css
  src/components/postpage/MainSection/MainSection.jsx
  src/components/postpage/MainSection/MainSection.module.css
  src/components/postpage/Question/Question.jsx
  src/components/postpage/Question/Question.module.css
  src/components/postpage/QuestionBox/QuestionBox.jsx
  src/components/postpage/QuestionBox/QuestionBox.module.css
  src/pages/post/PostPage.jsx
  src/pages/post/PostPage.module.css
  src/utils/getElapsedTime.js
Labels: 추가 기능 구현 중

#27 Feat: Answer 페이지 구현
  src/components/common/FeedCardAnswer/Answer.jsx
  src/components/common/FeedCardAnswer/Answer.module.css
  src/components/common/FeedCardAnswer/Answer/Answer.jsx
  src/components/common/FeedCardAnswer/Answer/Answer.module.css
  src/components/common/FeedCardAnswer/AnswerLayout/AnswerLayout.jsx
  src/components/common/FeedCardAnswer/AnswerLayout/AnswerLayout.module.css
  src/components/common/FeedCardAnswer/AnswerTextArea/AnswerTextArea.jsx
  src/components/common/FeedCardAnswer/AnswerTextArea/AnswerTextArea.module.css
  src/components/common/ShareBox/LinkBox.jsx
  src/components/common/ShareBox/ShareBox.jsx
  src/components/page-layout/QuestionPage/Layout/Header.jsx
  src/components/page-layout/QuestionPage/Layout/Header.module.css
  src/components/page-layout/QuestionPage/Layout/util.js
  src/components/page-layout/QuestionPage/Main/AnswerMain.jsx
  src/components/page-layout/QuestionPage/Main/AnswerMain.module.css
  src/components/postpage/FeedCard/FeedCard.jsx
  src/hooks/useQuestion.js
  src/images/QuestionHeaderImg.png
  src/main.jsx
  src/pages/answer/AnswerPage.jsx
  src/styles/global.css
Labels: 추가 기능 구현 중

#25 Feat: list 페이지 구현
  src/components/common/ButtonBox/ButtonBox.module.css
  src/components/common/DropdownOrder/DropdownOrder.jsx
  src/components/common/DropdownOrder/DropdownOrder.module.css
  src/components/common/Pagenation/feature-card-pagenation/CardPagenation.jsx
  src/components/common/Pagenation/feature-card-pagenation/CardPagenation.module.css
  src/components/common/Pagenation/ui-pagenation-wrap/PagenationWrap.jsx
  src/components/common/Pagenation/ui-pagenation-wrap/PagenationWrap.module.css
  src/components/common/Pagenation/ui-pagenation/Pagenation.jsx
  src/components/common/Pagenation/ui-pagenation/Pagenation.module.css
  src/components/common/Pagenation/ui-pagenation/util.js
  src/components/common/UserCard/data-access-card/test.js
  src/components/common/UserCard/ui-card/UserCard.jsx
  src/components/common/UserCard/ui-card/UserCard.module.css
  src/hooks/useIsTabletSize.js
  src/pages/list/ListPage.jsx
  src/pages/list/ListPage.module.css
Labels: 리뷰 요청
